apiVersion: v1
kind: Service
metadata:
  name: {{ include "chess.backendName" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "chess.backendName" . }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
