apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chess.frontendName" . }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "chess.frontendName" . }}
  template:
    metadata:
      labels:
        app: {{ include "chess.frontendName" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          ports:
            - containerPort: 80
