apiVersion: v1
kind: Service
metadata:
  name: {{ include "chess.frontendName" . }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "chess.frontendName" . }}
  ports:
    - name: http
      port: 80
      targetPort: 80
