apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.roleBinding }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccount }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.role }}
  apiGroup: rbac.authorization.k8s.io
