apiVersion: v2
name: chess
description: Chess engine demo with backend, worker, and monitoring
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: kube-prometheus-stack
    version: "55.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"

  - name: redis
    version: "19.6.0"
    repository: "https://charts.bitnami.com/bitnami"
