apiVersion: v1
kind: Service
metadata:
  name: {{ include "chess.workerName" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "chess.workerName" . }}
  ports:
    - name: metrics
      port: 9000
      targetPort: 9000
